# Prototype generated by Claude AI

from flask import Flask, request, jsonify
from flask_cors import CORS

app = Flask(__name__)
# Enable CORS to allow Chrome extension to communicate
CORS(app)

@app.route('/query', methods=['POST'])
def handle_query():
    """Handle queries from the Chrome extension"""
    data = request.get_json()
    query = data.get('query', '')

    print(f"Received query: {query}")

    # Do the presidio processing here, then return pdf

    # Send response back to extension
    return jsonify({
        'status': 'success',
        'message': 'You have successfully communicated with the local server in your chrome extension',
        'received_query': query
    })

@app.route('/health', methods=['GET'])
def health_check():
    """Health check endpoint"""
    return jsonify({'status': 'running'})

if __name__ == '__main__':
    print("Starting local server on http://localhost:5000")
    print("Server is ready to receive requests from Chrome extension")
    app.run(host='localhost', port=5000, debug=True)